import React from 'react';
import ConceptBlock from '../../../components/content/ConceptBlock.jsx';
import AnalogyBlock from '../../../components/content/AnalogyBlock.jsx';
import WarningBlock from '../../../components/content/WarningBlock.jsx';
import ExerciseBlock from '../../../components/content/ExerciseBlock.jsx';

export default function SlidingWindowSection() {
  return (
    <div className="prose-agents">
      <p>
        Conversations grow; context windows do not. The sliding window is the most
        common technique for managing this tension — rather than letting the window
        overflow, older content is progressively rolled out while newer content rolls in.
      </p>

      <ConceptBlock title="Sliding Context Window" number="Concept 5.13">
        A sliding window maintains a fixed-size view of the conversation by discarding
        or compressing the oldest turns as new ones are added. In a hard sliding window,
        turns beyond a fixed count are simply dropped. In a soft sliding window,
        dropped turns are first summarized and the summary is carried forward.
        The soft variant preserves continuity; the hard variant is simpler but risks
        losing critical information.
      </ConceptBlock>

      <AnalogyBlock title="The Ship's Log">
        A ship's captain keeps a detailed log of every day's events. As the voyage
        extends, old detailed entries are condensed into weekly summaries, and those
        summaries into monthly ones. The captain always has access to recent detail
        and older summary — never a complete blank. A soft sliding window follows
        this pattern: detail near the present, summary further back.
      </AnalogyBlock>

      <p>
        Sliding window parameters that must be tuned: the <strong>window size</strong>
        (how many recent turns to keep in full), the <strong>summary granularity</strong>
        (how many turns per summary chunk), and the <strong>summary trigger</strong>
        (how full the window must get before summarization runs). These parameters
        interact — a large window with coarse summarization wastes space; a small
        window with fine summarization adds latency.
      </p>

      <WarningBlock title="Dropped Context Is Silent">
        When a hard sliding window drops a turn, there is no indication to the agent
        that information is missing. The agent proceeds as if it always knew only
        what is currently in the window. This can cause inconsistent responses —
        the agent contradicts something it "said" but can no longer see.
        Soft summarization is always preferable for continuity-sensitive tasks.
      </WarningBlock>

      <ExerciseBlock
        title="Sliding Window Practice"
        exercises={[
          {
            id: 'e5-13-1',
            difficulty: 'beginner',
            question: 'Describe the difference between a hard sliding window and a soft sliding window. In what type of task would each be acceptable?',
            hint: 'Consider what continuity means for different task types.',
            solution: 'Hard: oldest turns deleted entirely. Acceptable for stateless Q&A where each question is independent and context from five turns ago is irrelevant. Soft: oldest turns replaced with a summary. Required for tasks involving ongoing goals, commitments, or accumulated research where earlier turns inform current decisions.',
          },
          {
            id: 'e5-13-2',
            difficulty: 'intermediate',
            question: 'A soft sliding window summarizes every 10 turns. The summary is generated by the same model being summarized. What are two failure modes of this approach?',
            hint: 'Think about what the model might lose or distort during summarization.',
            solution: 'Failure 1: Compounding errors — if the summary omits or distorts a fact, every subsequent summary inherits the error until the original is unrecoverable. Failure 2: Selective memory — the model\'s summarization may unconsciously deprioritize information that seems unimportant mid-conversation but becomes critical later (e.g., an early preference stated by the user). Mitigation: use structured summarization templates that require capturing specific categories of information.',
          },
          {
            id: 'e5-13-3',
            difficulty: 'advanced',
            question: 'Design a sliding window strategy for a coding agent that must maintain awareness of (a) the user\'s original task, (b) which files have been modified, and (c) the current error state. How do you ensure none of these are ever lost to compression?',
            hint: 'Consider pinning critical state outside the sliding window.',
            solution: 'Maintain a "persistent state block" at the top of the system prompt that is updated (not compressed) as the session progresses. This block contains: (1) original task description, immutable, (2) a file modification log that appends new entries, (3) current error state, overwritten on each change. The sliding window applies only to conversational turns and tool results. Critical state is never subject to summarization — it lives in the persistent block, outside the window.',
          },
        ]}
      />
    </div>
  );
}
