export const subject = {
  id: 'agent-runtime',
  title: 'The Agent Runtime',
  description: 'The engine that turns a language model into a working agent — initialization, conversation loops, and resource management.',
  icon: '⚙️',
  colorHex: '#6366f1',
  difficulty: 'intermediate',
  estimatedHours: 12,
  prerequisites: ['thinking-in-agents', 'tools'],
  chapters: [
    {
      id: 'c1-initialization',
      title: 'Initialization',
      description: 'What happens before the first turn — bootstrap, trust gates, and environment detection.',
      difficulty: 'intermediate',
      estimatedMinutes: 100,
      sections: [
        { id: 's1-cold-start', title: 'Cold Start', description: 'What happens before the first turn — loading config, checking environment, preparing tools.', difficulty: 'intermediate', readingMinutes: 12 },
        { id: 's2-bootstrap-pipeline', title: 'The Bootstrap Pipeline', description: 'Ordered steps for safe startup — why initialization order matters.', difficulty: 'intermediate', readingMinutes: 12 },
        { id: 's3-trust-gates', title: 'Trust Gates', description: 'Running sensitive setup only after explicit approval from the user.', difficulty: 'intermediate', readingMinutes: 10, buildsOn: 'trust-and-safety/c2-permission-models/s1-ask-every-time' },
        { id: 's4-parallel-init', title: 'Parallel Initialization', description: 'Doing multiple setup tasks at once to reduce startup time.', difficulty: 'intermediate', readingMinutes: 10 },
        { id: 's5-environment-detection', title: 'Environment Detection', description: 'Adapting to platform, shell, and runtime — agents that know where they are.', difficulty: 'intermediate', readingMinutes: 10 },
      ],
    },
    {
      id: 'c2-conversation-engine',
      title: 'The Conversation Engine',
      description: 'Turns, message history, tool loops, and streaming — the core of agent execution.',
      difficulty: 'intermediate',
      estimatedMinutes: 100,
      sections: [
        { id: 's1-turns', title: 'Turns', description: 'The fundamental unit of agent work — one cycle of input, reasoning, and output.', difficulty: 'intermediate', readingMinutes: 10 },
        { id: 's2-message-history', title: 'Message History', description: 'The agent short-term memory — what happened in this conversation.', difficulty: 'intermediate', readingMinutes: 10 },
        { id: 's3-tool-loop', title: 'The Tool Loop', description: 'Call, observe, reason, repeat — how agents iterate toward a solution.', difficulty: 'intermediate', readingMinutes: 12 },
        { id: 's4-stop-conditions', title: 'Stop Conditions', description: 'Knowing when the work is done — task completion, budget limits, and explicit stops.', difficulty: 'intermediate', readingMinutes: 10 },
        { id: 's5-streaming', title: 'Streaming', description: 'Delivering results incrementally — why users should see progress in real time.', difficulty: 'intermediate', readingMinutes: 10 },
      ],
    },
    {
      id: 'c3-resource-management',
      title: 'Resource Management',
      description: 'Token budgets, cost tracking, rate limits, and session persistence.',
      difficulty: 'intermediate',
      estimatedMinutes: 100,
      sections: [
        { id: 's1-token-budgeting', title: 'Token Budgeting', description: 'Working within finite context — allocating space wisely across turns.', difficulty: 'intermediate', readingMinutes: 12 },
        { id: 's2-context-compaction', title: 'Context Compaction', description: 'Summarizing old messages to free space for new work.', difficulty: 'intermediate', readingMinutes: 12 },
        { id: 's3-cost-tracking', title: 'Cost Tracking', description: 'Understanding what agent work costs — tokens, time, and money.', difficulty: 'intermediate', readingMinutes: 10 },
        { id: 's4-rate-limits', title: 'Rate Limits and Backoff', description: 'Handling API constraints gracefully — retries, exponential backoff, and queuing.', difficulty: 'intermediate', readingMinutes: 10 },
        { id: 's5-session-persistence', title: 'Session Persistence', description: 'Saving state for later resumption — transcripts, checkpoints, and replay.', difficulty: 'intermediate', readingMinutes: 10 },
      ],
    },
  ],
}
